### ISSUE TITLE
不支持在子模块中使用css modules

### ISSUE THREAD

**Issue by qihengzhw** [gxlmyacc/import-remote#149]
在官方的例子中，比如/demo/demo_remote_app)/app2/，在webpack.config.js中添加less支持，然后在button.js中引入import styles from './button.less'，编写简单的button.less文件，添加一个样式，然后在button.js中引入

在app1模块中远程引入app2，就会报出如下错误：
remote.js:603 warning:[import-remote:remote]module "@basic-host-remote/app2" need external "0" !
runtime5.js:142 [import-remote]module[0] not exist!
app.js:246 Uncaught (in promise) TypeError: $refs.hoc is not a function

本人邮箱：532657367@qq.com

**Comment by qihengzhw** [comment]
> 

button.js，使用css module，然后再写一个button2.js，引用button.js，button2.js不引入css module，然后导出button2，这时在app1中使用是正常的

**Comment by gxlmyacc** [comment]
好的，我试试看能不能重现。你可以先确定下用的是不是最新版，目前最新版是0.0.19-alpha.5

**Comment by gxlmyacc** [comment]
@qihengzhw , 问题原因找到了，请升级到0.0.19-alpha.6试试，同时我也更新了下demo。非常感谢你的反馈
