### ISSUE TITLE
使用copy-webpack-plugin时，会不断拷贝入口文件

### ISSUE THREAD

**Issue by zuilafeng** [gxlmyacc/import-remote#185]
import-remote/plugin插件使用后，生成的静态资源dist，copy-webpack-plugin拷贝dist目录下的文件到指定目录, webpack使用dev-server一直在watch;
现象: 刚开始会正常拷贝，后面一直死循环拷贝入口文件

**Comment by gxlmyacc** [comment]
copy-webpack-plugin这个插件我也在用，没遇到你说的情况。也许和webpack、copy-webpack-plugin的版本或者配置有关，能不能整理出来一个打包的demo让我试试呢？

**Comment by zuilafeng** [comment]
> 

后面换了一个插件filemanager-webpack-plugin， 是可行的

**Comment by zuilafeng** [comment]
> copy-webpack-plugin这个插件我也在用，没遇到你说的情况。也许和webpack、copy-webpack-plugin的版本或者配置有关，能不能整理出来一个打包的demo让我试试呢？

后面换了一个插件filemanager-webpack-plugin，是可行的；之前webpack， copy-webpack-plugin用的都是最新版本

**Comment by gxlmyacc** [comment]
> > copy-webpack-plugin这个插件我也在用，没遇到你说的情况。也许和webpack、copy-webpack-plugin的版本或者配置有关，能不能整理出来一个打包的demo让我试试呢？
> 
> 后面换了一个插件filemanager-webpack-plugin，是可行的；之前webpack， copy-webpack-plugin用的都是最新版本

嗯嗯，那就好。估计可能和copy-webpack-plugin配置有关系吧 : -）

**Comment by gxlmyacc** [comment]
> > copy-webpack-plugin这个插件我也在用，没遇到你说的情况。也许和webpack、copy-webpack-plugin的版本或者配置有关，能不能整理出来一个打包的demo让我试试呢？
> 
> 后面换了一个插件filemanager-webpack-plugin，是可行的；之前webpack， copy-webpack-plugin用的都是最新版本

嗯嗯，那就好。估计可能和copy-webpack-plugin配置有关系吧 : -）
