### ISSUE TITLE
remote中options的beforeSource回调并没有触发，就直接返回source

### ISSUE THREAD

**Issue by zuilafeng** [gxlmyacc/import-remote#186]
![image](https://user-images.githubusercontent.com/10205938/218957364-03ed1472-d489-4448-91ee-b596fc34968f.png)
目前我想实现的是给远程模块做沙箱处理，不破坏宿主环境的window对象，本计划改module.default，但一旦字符串化函数，会丢失函数的上下文环境，所以想得到远程模块的js完整source处理成proxy window + new Function的实现，但我发现remote的beforeSource回调并没有触发（截图中的540行代码），尽管我已经传了

**Comment by gxlmyacc** [comment]
确实存在问题，我更新了个版本0.1.0-alpha.9，麻烦更新到这个版本试试。
不过建议还是尽量不要做沙箱处理，之前我们有个项目用乾坤做了沙箱处理，出现各种莫名其妙的问题。如果有其他办法的话，还是尽量用其他解决办法吧。
另外，import-remote本身也内置了一些简单的沙箱处理，比如RemoteView组件、插件的globalToScopes配置。

**Comment by zuilafeng** [comment]
> 确实存在问题，我更新了个版本0.1.0-alpha.9，麻烦更新到这个版本试试。 不过建议还是尽量不要做沙箱处理，之前我们有个项目用乾坤做了沙箱处理，出现各种莫名其妙的问题。如果有其他办法的话，还是尽量用其他解决办法吧。 另外，import-remote本身也内置了一些简单的沙箱处理，比如RemoteView组件、插件的globalToScopes配置。

这确实修复了，感谢帮忙！只是目前项目的特殊性，globalToScopes需要配置用到的全局变量，目前对我的场景帮助不大，正在尝试使用windowProxy: {
                  context: {
                    window: proxyWindow
                  }
            } 改写requireFromStr方法，但遇到了一些问题，还是很感谢你的帮忙
