### ISSUE TITLE
webpack5.0 production打包生成的manifest文件会丢失entryId, entryFile

### ISSUE THREAD

**Issue by zuilafeng** [gxlmyacc/import-remote#187]
webpack部分配置: 
```js
{
  mode: 'production',
  optimization: {
      minimize: false,
      minimizer: [
        new TerserPlugin({
          terserOptions: {
            ecma: 6,
            compress: false,
            mangle: false,
            output: {
              comments: false,
              beautify: false
            }
          },
          extractComments: false,
        })
      ]
    },
  plugins: [
   new ImportRemotePlugin({
        template: 'auto',
        filename: 'index.js'
      })
  ]
}
```
prd生成后的index.js文件
```js
module.exports=function(){return {"timestamp":1677638436581,"name":"yoe-workspace","version":1,"webpackVersion":5,"mode":"production","devtool":false,"moduleVersion":"1.0.0","hash":"6a8933a09b313279af11","hot":false,"nodeModulesPath":"node_modules","entryFile":"","entryId":0,"windowObject":"self","globalObject":"__context__","jsonpFunction":"webpackChunkyoe_workspace","hotUpdateGlobal":"webpackHotUpdateyoe_workspace","uniqueName":"yoe-workspace","scopeName":"yoe-workspace","publicPath":"","shareModules":[],"remotes":{"hasJsMatcher":null,"chunkMapping":{},"idToExternalAndNameMapping":{},"initCodePerScope":{},"initialConsumes":[],"moduleIdToSourceMapping":{},"chunkToModuleMapping":{},"runtimeName":""},"externals":[{"id":644,"name":"react","var":"react","path":"node_modules/react/index.js"}],"jsChunks":{"232":"index-2550c.js"},"cssChunks":{},"entrys":{"css":[],"js":["index-2550c.js"],"ids":[232]},"meta":{}};};module.exports['iref']=true;
```

dev生成后的index.js文件:
```js
module.exports=function(){return {"timestamp":1677638770836,"name":"yoe-workspace","version":1,"webpackVersion":5,"mode":"development","devtool":false,"moduleVersion":"1.0.0","hash":"fa231b04c12a440d3f7e","hot":false,"nodeModulesPath":"node_modules","entryFile":"./node_modules/react/cjs/react-jsx-runtime.development.js","entryId":"./plugins/officialRedPlugin/index.ts","windowObject":"self","globalObject":"__context__","jsonpFunction":"webpackChunkyoe_workspace","hotUpdateGlobal":"webpackHotUpdateyoe_workspace","uniqueName":"yoe-workspace","scopeName":"yoe-workspace","publicPath":"","shareModules":[],"remotes":{"hasJsMatcher":null,"chunkMapping":{},"idToExternalAndNameMapping":{},"initCodePerScope":{},"initialConsumes":[],"moduleIdToSourceMapping":{},"chunkToModuleMapping":{},"runtimeName":""},"externals":[{"id":"react","name":"react","var":"react","path":"node_modules/react/index.js"}],"jsChunks":{"officialRedPlugin":"index-50d11.js"},"cssChunks":{},"entrys":{"css":[],"js":["index-50d11.js"],"ids":["officialRedPlugin"]},"meta":{}};};module.exports['iref']=true;
```

用production包跑报错:
![image](https://user-images.githubusercontent.com/10205938/222032488-38ff0f61-b235-4a0a-b417-cd252f7e8412.png)

**Comment by gxlmyacc** [comment]
我试了下，没问题呀
生成的是这样的
```js
module.exports = function () {
  return {
    timestamp: 1677666195959,
    name: test,
    version: 1,
    webpackVersion: 5,
    mode: production,
    devtool: false,
    moduleVersion: 0.0 .0,
    hash: 89 b3231cb07cf97bf950,
    hot: false,
    nodeModulesPath: node_modules,
    entryFile: src / index.js,
    entryId: 138,
    windowObject: self,
    globalObject: __context__,
    jsonpFunction: webpackChunktest,
    hotUpdateGlobal: webpackHotUpdatetest,
    uniqueName: test,
    scopeName: test,
    publicPath: /,shareModules:[],remotes:{hasJsMatcher:null,chunkMapping:{},idToExternalAndNameMapping:{},initCodePerScope:{},initialConsumes:[],moduleIdToSourceMapping:{},chunkToModuleMapping:{},runtimeName:},externals:[],jsChunks:{179:assets/main - 24 c22.js
  }, cssChunks: {}, entrys: {
    css: [],
    js: [assets / main - 24 c22.js],
    ids: [179]
  }, meta: {}
};
};
module.exports['iref'] = true;
```
你下载这个项目，打包下试试？
https://stackblitz.com/edit/js-k2n17x?file=package.json,webpack.config.js,src%2Findex.js

**Comment by zuilafeng** [comment]
> 我试了下，没问题呀 生成的是这样的
> 
> ```js
> module.exports = function () {
>   return {
>     timestamp: 1677666195959,
>     name: test,
>     version: 1,
>     webpackVersion: 5,
>     mode: production,
>     devtool: false,
>     moduleVersion: 0.0 .0,
>     hash: 89 b3231cb07cf97bf950,
>     hot: false,
>     nodeModulesPath: node_modules,
>     entryFile: src / index.js,
>     entryId: 138,
>     windowObject: self,
>     globalObject: __context__,
>     jsonpFunction: webpackChunktest,
>     hotUpdateGlobal: webpackHotUpdatetest,
>     uniqueName: test,
>     scopeName: test,
>     publicPath: /,shareModules:[],remotes:{hasJsMatcher:null,chunkMapping:{},idToExternalAndNameMapping:{},initCodePerScope:{},initialConsumes:[],moduleIdToSourceMapping:{},chunkToModuleMapping:{},runtimeName:},externals:[],jsChunks:{179:assets/main - 24 c22.js
>   }, cssChunks: {}, entrys: {
>     css: [],
>     js: [assets / main - 24 c22.js],
>     ids: [179]
>   }, meta: {}
> };
> };
> module.exports['iref'] = true;
> ```
> 
> 你下载这个项目，打包下试试？ https://stackblitz.com/edit/js-k2n17x?file=package.json,webpack.config.js,src%2Findex.js


这个尝试了没有问题，但我改了下，可以复现 https://stackblitz.com/edit/js-fyepjy?file=src/index.js
而且，即使我配置关闭一切的压缩、混淆，但webpack内部好像只要读取到mode: production，就默认给处理成压缩、混淆，完全忽略了我的配置

**Comment by gxlmyacc** [comment]
你升级到 "import-remote": "^0.1.0-alpha.9",版本试试，我用这个最新版是没问题的

**Comment by zuilafeng** [comment]
> 你升级到 "import-remote": "^0.1.0-alpha.9",版本试试，我用这个最新版是没问题的
感谢回复！
刚刚试过了，还是存在的；你有正常的外部链接不？
你用https://stackblitz.com/edit/js-fyepjy?file=src/index.js测试是正常的么?

**Comment by zuilafeng** [comment]
> 你升级到 "import-remote": "^0.1.0-alpha.9",版本试试，我用这个最新版是没问题的


感谢回复！
刚刚试过了，还是存在的；你有正常的外部链接不？
你用[https://stackblitz.com/edit/js-fyepjy?file=src/index.js测试是正常的么](https://stackblitz.com/edit/js-fyepjy?file=src/index.js%E6%B5%8B%E8%AF%95%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%E4%B9%88)?

**Comment by zuilafeng** [comment]
> 你升级到 "import-remote": "^0.1.0-alpha.9",版本试试，我用这个最新版是没问题的

感谢回复！
刚刚试过了，还是存在的；你有正常的外部链接不？
你用[https://stackblitz.com/edit/js-fyepjy?file=src/index.js](https://stackblitz.com/edit/js-fyepjy?file=src/index.js%E6%B5%8B%E8%AF%95%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%E4%B9%88) 测试是正常的么?

**Comment by gxlmyacc** [comment]
> > 你升级到 "import-remote": "^0.1.0-alpha.9",版本试试，我用这个最新版是没问题的
> 
> 感谢回复！ 刚刚试过了，还是存在的；你有正常的外部链接不？ 你用[https://stackblitz.com/edit/js-fyepjy?file=src/index.js](https://stackblitz.com/edit/js-fyepjy?file=src/index.js%E6%B5%8B%E8%AF%95%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%E4%B9%88) 测试是正常的么?

我就是用你的这个项目打包试的。你这个项目里有一些编译错误，解决后，能正常打包，出来入口文件是这样的：
```js
module.exports = function (r, o) {
  var m = {
    "timestamp": 1678275294340,
    "name": "test",
    "version": 1,
    "webpackVersion": 5,
    "mode": "production",
    "devtool": false,
    "moduleVersion": "0.0.0",
    "hash": "6c2b1b62247150d881be",
    "hot": false,
    "nodeModulesPath": "node_modules",
    "entryFile": "",
    "entryId": 657,
    "windowObject": "self",
    "globalObject": "__context__",
    "jsonpFunction": "webpackChunktest",
    "hotUpdateGlobal": "webpackHotUpdatetest",
    "uniqueName": "test",
    "scopeName": "test",
    "publicPath": "",
    "shareModules": [],
    "remotes": {
      "hasJsMatcher": null,
      "chunkMapping": {},
      "idToExternalAndNameMapping": {},
      "initCodePerScope": {},
      "initialConsumes": [],
      "moduleIdToSourceMapping": {},
      "chunkToModuleMapping": {},
      "runtimeName": ""
    },
    "externals": [],
    "jsChunks": {
      "179": "assets/main-b700c.js"
    },
    "cssChunks": {},
    "entrys": {
      "css": [],
      "js": ["assets/main-b700c.js"],
      "ids": [179]
    },
    "meta": {}
  };
  return m
};
module.exports['iref'] = true;
```
entryId是有值的，不用关心entryFile，那个在devlopment打包时才有效。

**Comment by zuilafeng** [comment]
> > > 你升级到 "import-remote": "^0.1.0-alpha.9",版本试试，我用这个最新版是没问题的
> > 
> > 
> > 感谢回复！ 刚刚试过了，还是存在的；你有正常的外部链接不？ 你用[https://stackblitz.com/edit/js-fyepjy?file=src/index.js](https://stackblitz.com/edit/js-fyepjy?file=src/index.js%E6%B5%8B%E8%AF%95%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%E4%B9%88) 测试是正常的么?
> 
> 我就是用你的这个项目打包试的。你这个项目里有一些编译错误，解决后，能正常打包，出来入口文件是这样的：
> 
> ```js
> module.exports = function (r, o) {
>   var m = {
>     "timestamp": 1678275294340,
>     "name": "test",
>     "version": 1,
>     "webpackVersion": 5,
>     "mode": "production",
>     "devtool": false,
>     "moduleVersion": "0.0.0",
>     "hash": "6c2b1b62247150d881be",
>     "hot": false,
>     "nodeModulesPath": "node_modules",
>     "entryFile": "",
>     "entryId": 657,
>     "windowObject": "self",
>     "globalObject": "__context__",
>     "jsonpFunction": "webpackChunktest",
>     "hotUpdateGlobal": "webpackHotUpdatetest",
>     "uniqueName": "test",
>     "scopeName": "test",
>     "publicPath": "",
>     "shareModules": [],
>     "remotes": {
>       "hasJsMatcher": null,
>       "chunkMapping": {},
>       "idToExternalAndNameMapping": {},
>       "initCodePerScope": {},
>       "initialConsumes": [],
>       "moduleIdToSourceMapping": {},
>       "chunkToModuleMapping": {},
>       "runtimeName": ""
>     },
>     "externals": [],
>     "jsChunks": {
>       "179": "assets/main-b700c.js"
>     },
>     "cssChunks": {},
>     "entrys": {
>       "css": [],
>       "js": ["assets/main-b700c.js"],
>       "ids": [179]
>     },
>     "meta": {}
>   };
>   return m
> };
> module.exports['iref'] = true;
> ```
> 
> entryId是有值的，不用关心entryFile，那个在devlopment打包时才有效。


确实如此，本地上传的时候，可能有些没必要的东西忘记删除了，报歉报歉
刚才试了下，确实解决了问题
