### ISSUE TITLE
dependencies里的依赖冲突

### ISSUE THREAD

**Issue by xty1992a** [gxlmyacc/import-remote#20]
写在dependencies里的依赖会在安装时一起安装，导致和原有的冲突。应该放到peerDependencies吧。。。

**Comment by gxlmyacc** [comment]
如果放到peerDependencies里，不会主动安装的，用户很可能会忽略掉对应的警告信息。
而且，问题应该应该也不大，大版本区别，yarn、npm这些应该会自动区分出来，安装多个依赖包，让它们各种使用自己的。当然，出现冲突的可能性也是存在的。但目前我没遇到过。

**Comment by xty1992a** [comment]
不是，@babel/core这种依赖显然不应该放dependencies吧，Babel全家桶都是编译时的，放devdep才对。

除此之外，假设你的运行时依赖和用户的依赖出现了版本的不同。最终产物应该是会同时存在两份，这样是没有必要的，这个库的目标用户本身也是webpack的使用者，本身对优化有需求，恐怕不能接受这种情况。

**Comment by gxlmyacc** [comment]
我把babel的那些插件移到devDependencies吧，但是@babel/core还是保留下，因为运行时包依赖它。

  > 除此之外，假设你的运行时依赖和用户的依赖出现了版本的不同。最终产物应该是会同时存在两份，这样是没有必要的，这个库的目标用户本身也是webpack的使用者，本身对优化有需求，恐怕不能接受这种情况。

一般的npm运行时包都是将依赖的babel/core内容打包到成果里去了。而我只是对代码做了转义，这才依赖使用者环境的@babel/core。这样做的初衷也是：如果使用者的babel/core和我一致，那他可以少打包一些资源；如果版本不一样，那也只是和其他npm方式一样而已；更何况我在dependencies配置的版本都带^，也就是只要求大版本相同而已
